version: "3.9"

services:
  devopsdb:
    image: allakondaswapna/newrepo:database
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - Docker-db:/var/lib/mysql

  application:
    image: allakondaswapna/newrepo:application
    ports:
      - "2222:8080"
    networks:
      - mynetwork
    volumes:
      - Docker-app:/usr/local/tomcat/webapps
    depends_on:
      - devopsdb

networks:
  mynetwork:
    driver: overlay

volumes:
  Docker-db:
  Docker-app:
